CREATE TABLE IF NOT EXISTS APP_USER (
  ID VARCHAR(20) PRIMARY KEY,
  FULLNAME VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS TODO (
  ID VARCHAR(50) PRIMARY KEY,
  TITLE VARCHAR(100),
  IS_DONE BOOLEAN,
  CREATOR_ID VARCHAR(20),
  CONSTRAINT FK_CREATOR_ID FOREIGN KEY (CREATOR_ID) REFERENCES APP_USER(ID)
);
