CREATE TABLE IF NOT EXISTS AUTH (
  EMAIL VARCHAR(50) PRIMARY KEY,
  PASS_HASH VARCHAR(100),
  ID VARCHAR(100) UNIQUE
);

CREATE TABLE IF NOT EXISTS APP_USER (
  ID VARCHAR(100) PRIMARY KEY,
  FULLNAME VARCHAR(50),
  CONSTRAINT FK_AUTH_ID FOREIGN KEY (ID) REFERENCES AUTH(ID)
);

CREATE TABLE IF NOT EXISTS TODO (
  ID VARCHAR(100) PRIMARY KEY,
  TITLE VARCHAR(100),
  IS_DONE BOOLEAN,
  CREATOR_ID VARCHAR(20),
  CONSTRAINT FK_CREATOR_ID FOREIGN KEY (CREATOR_ID) REFERENCES APP_USER(ID)
);

CREATE TABLE IF NOT EXISTS APP_SESSION (
  U_ID VARCHAR(100) PRIMARY KEY,
  S_ID VARCHAR(100),
  CONSTRAINT FK_S_ID FOREIGN KEY (U_ID) REFERENCES AUTH(ID)
);
